" disable compatibility with vi - required by vundle
set nocompatible
" turns off filetype while vundle does its thing - required by vundle
filetype off
" sets vundle runtime
set rtp+=~/Dropbox/dotfiles/vim/bundle/Vundle.vim
" initializes vundle, run with :PluginInstall
call vundle#begin()
" list vundle packages
Plugin 'VundleVim/Vundle.vim'
" YCM requires different pythons per OS
if has('macunix')
  Plugin 'Valloric/YouCompleteMe', { 'name': 'YouCompleteMe-OSX' }
elseif has('unix')
  Plugin 'Valloric/YouCompleteMe', { 'name': 'YouCompleteMe-Linux' }
elseif has('win32')
  Plugin 'Valloric/YouCompleteMe', { 'name': 'YouCompleteMe-Windows' }
endif
Plugin 'gioele/vim-autoswap'
Plugin 'jiangmiao/auto-pairs'
Plugin 'scrooloose/nerdtree'
Plugin 'genoma/vim-less'
Plugin 'mattn/emmet-vim'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'suan/vim-instant-markdown'
Plugin 'tpope/vim-rails'
Plugin 'vim-ruby/vim-ruby'
Plugin 'scrooloose/nerdcommenter'
Plugin 'itchyny/lightline.vim'
Plugin 'guns/vim-clojure-static'
Plugin 'guns/vim-clojure-highlight'
Plugin 'tpope/vim-fireplace'
Plugin 'eapache/rainbow_parentheses.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
Plugin 'pangloss/vim-javascript'
Plugin 'othree/javascript-libraries-syntax.vim'
Plugin 'mustache/vim-mustache-handlebars'
Plugin 'marijnh/tern_for_vim'
Plugin 'scrooloose/syntastic'
Plugin 'valloric/matchtagalways'
Plugin 'terryma/vim-expand-region'
Plugin 'yankring.vim'
Plugin 'rking/ag.vim'
Plugin 'osyo-manga/vim-over'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'edkolev/tmuxline.vim'
Plugin 'beloglazov/vim-online-thesaurus'
Plugin 'reedes/vim-pencil'
Plugin 'reedes/vim-litecorrect'
Plugin 'junegunn/goyo.vim'
Plugin 'amix/vim-zenroom2'
Plugin 'mhinz/vim-startify'
Plugin 'junegunn/limelight.vim'
Plugin 'mxw/vim-jsx'
Plugin 'elliotec/rapid.vim'
call vundle#end()
" Re-enable filetype when Vundle is done
filetype plugin indent on
" Enable syntax highlighting
syntax on
set t_Co=256
" Ignores case sensitivity, for smartcase
set ignorecase
" for folding properly
set foldmethod=syntax
set foldcolumn=1
set nofoldenable
set foldnestmax=10
" Incremental search
set incsearch
" Highlight search result
set hlsearch
" Enable mouse usage (all modes)
set mouse=a
" Use relative line numbers
"set relativenumber
" except for current line
set number
" Enable smart case matching
set smartcase
" Keep encoding utf-8
set encoding=utf-8
set fileencoding=utf-8
" Backspace kills end of line and moves to previous
set backspace=indent,eol,start
" Keep buffers in the background when abandoned
set hidden
" ignore lots of files
set wildignore+=*.jpg,*.jpeg,*.gif,*.png,*.mov,*.pdf,*.psd,*.ai
set wildignore+=*.ppt,*.pptx,*.doc,*.docx,*.xls,*.xlsx
" enable matchit plugin which ships with vim and enhances '%'
runtime macros/matchit.vim
" Show me what I'll do
set showcmd
" Enble autoread, some weird magic here that works well.
set autoread
augroup checktime
    au!
    if !has("gui_running")
        autocmd BufEnter        * silent! checktime
        autocmd CursorHold      * silent! checktime
        autocmd CursorHoldI     * silent! checktime
        autocmd CursorMoved     * silent! checktime
        autocmd CursorMovedI    * silent! checktime
        autocmd FocusGained     * silent! checktime
    endif
augroup END
" Use unix line endings
set fileformat=unix
" always show status bar
set laststatus=2
" only show status in status bar
set noshowmode
" autoindent based on line above
set autoindent
" use spaces instead of tabs (noexpandtab for opposite)
set expandtab
" for makefiles
autocmd FileType make set noexpandtab
" tabs are 2 spaces while reading and insert mode
set shiftwidth=2
set softtabstop=2
" size of a hard tabstop
set tabstop=2
" smarter indent for C-like languages
set smartindent
" show tabs with dashes and trailing spaces with dots
set listchars=tab:--,trail:·
set list
" keep cursor visible within 8 lines while scrolling
set scrolloff=8
" Swaps and backups go in tmp
set directory=~/.vim/tmp//
set backupdir=~/.vim/tmp//
" undo files and persistant undos
set undofile
set history=1000
set undodir=~/Dropbox/dotfiles/.vim/tmp/undo/
set undolevels=1000
set undoreload=10000
" Specify syntax on certain filetypes
autocmd BufNewFile,BufRead *.md,*.markdown setlocal ft=markdown
autocmd BufNewFile,BufRead *.less setlocal ft=less
autocmd BufNewFile,BufRead *.scss setlocal ft=scss
" autocomplete words with spell check
set complete+=kspell
" Remove trailing whitespace on save
function! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()
" Set current colorscheme (from .vim/colors/)
colorscheme molokai
" Set space as map leader
let mapleader = "\<Space>"
" map jj to esc
inoremap jj <ESC>
" clipboard bindings
set clipboard=unnamed
" better ways to get to beginning and end of line
nnoremap H 0
nnoremap L $
" expand region visual by repeating v rather than +
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
" map ,ev to edit vimrc
nnoremap <leader>ev :vsp $MYVIMRC<CR>
" save with <leader>w
nnoremap <leader>w :w<CR>
" set vim-over command to leader f
nnoremap <leader>f :OverCommandLine<CR>
" toggle nerdtree with ctrl-o
map <C-o> :NERDTreeToggle %:p:h<CR>
" tab and shift-tab do proper thing
vmap <Tab> >gv
vmap <S-Tab> <gv
" Make Y behave like other Capitals (C, D, etc.)
noremap Y y$
" rainbow parens always on
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
" dictionary path
set dictionary="/usr/dict/words"
" lightline settings
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'readonly', 'filename', 'modified' ] ],
      \  'right': [ [ 'lineinfo' ],
      \             [ 'percent' ],
      \             [ 'filetype' ] ]
      \ },
      \ 'component': {
      \   'readonly': '%{&readonly?"x":""}',
      \   'fugitive': '%{exists("*fugitive#head")?fugitive#head():""}'
      \ },
      \ 'component_visible_condition': {
      \   'fugitive': '(exists("*fugitive#head") && ""!=fugitive#head())'
      \ },
      \ 'separator': { 'left': '', 'right': '' },
      \ 'subseparator': { 'left': '|', 'right': '|' }
      \ }
" Swap lines up and down
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv
" Easy buffer switch
nmap <leader>l :bnext<CR>
nmap <leader>h :bprevious<CR>
" kill scratch buffer after selection is made
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif
"Destroy distractions
nnoremap <silent> <leader>z :Goyo<cr>
" use eslint for syntastic
let g:syntastic_javascript_checkers = ['eslint']
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" emmet expander
let g:user_emmet_expandabbr_key = '<c-y>'
" ag alwyas starts from project root
let g:ag_working_path_mode="r"
" create yankring history file in vim dir
let g:yankring_history_dir="~/.vim/"
" remove powerline symbols
let g:tmuxline_powerline_separators = 0
" writing mode on markdown files
autocmd bufread,bufnewfile *.md,*.markdown setlocal spell
autocmd bufread,bufnewfile *.md,*.markdown setlocal wrap
"autocmd bufread,bufnewfile *.md,*.markdown setlocal foldmethod=indent
autocmd bufread,bufnewfile *.md,*.markdown call litecorrect#init()
autocmd bufread,bufnewfile *.md,*.markdown call pencil#init({'wrap': 'soft'})
let g:vim_markdown_frontmatter = 1
augroup end
"let g:vim_markdown_folding_disabled=1
function! s:goyo_enter()
  silent !tmux set status off
  Goyo 100x90%
  Limelight
endfun
function! s:goyo_leave()
  silent !tmux set status on
  Limelight!
endfun
autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()
